assetic:
    assets:
        campaignchain_base_css:
            inputs:
                - "@CampaignChainCoreBundle/Resources/public/css/campaignchain/base.css"
                - "@CampaignChainCoreBundle/Resources/public/css/campaignchain/sidemenu.css"
        campaignchain_base_js:
            inputs:
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/base.js"
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/exception.js"
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/modal.js"
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/sidemenu.js"
                - "%campaignchain.bower.asset_dir%/campaignchaincore/ScrollToFixed/jquery-scrolltofixed.js"
        campaignchain_login_css:
            inputs:
                - "@CampaignChainCoreBundle/Resources/public/css/campaignchain/login.css"
        jquery_js:
            inputs:
                - "%kernel.root_dir%/../vendor/components/jquery/jquery.js"
            filters:
                - "?yui_js"
        moment_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/moment/moment.js"
                - "%campaignchain.bower.asset_dir%/campaignchaincore/moment-timezone/builds/moment-timezone-with-data.js"
        jquery_file_upload_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/jquery-file-upload/js/vendor/jquery.ui.widget.js"
                - "%campaignchain.bower.asset_dir%/campaignchaincore/jquery-file-upload/js/jquery.fileupload.js"
                - "%campaignchain.bower.asset_dir%/campaignchaincore/jquery-file-upload/js/jquery.fileupload-process.js"
                - "%campaignchain.bower.asset_dir%/campaignchaincore/jquery-file-upload/js/jquery.fileupload-validate.js"
        jquery_cropper_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/cropper/dist/cropper.js"
        jquery_cropper_css:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/cropper/dist/cropper.css"
        bootstrap_js:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js"
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js"
            filters:
                - "?yui_js"
        bootstrap_less:
            inputs:
                - "%kernel.root_dir%/../vendor/twbs/bootstrap/less/bootstrap.less"
            filters:
                - "lessphp"
                - "cssembed"
        bootstrap_glyphicons_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.ttf
            output: "fonts/glyphicons-halflings-regular.ttf"
        bootstrap_glyphicons_eot:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.eot
            output: "fonts/glyphicons-halflings-regular.eot"
        bootstrap_glyphicons_svg:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.svg
            output: "fonts/glyphicons-halflings-regular.svg"
        bootstrap_glyphicons_woff:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff
            output: "fonts/glyphicons-halflings-regular.woff"
        braincrafted_bootstrap:
            less_filter: "lessphp"
        select2_js:
            inputs:
                - "%kernel.root_dir%/../vendor/ivaynberg/select2/select2.js"
        select2_dependent_js:
            inputs:
                - "@CampaignChainCoreBundle/Resources/public/js/select2_select2_ajax.js"
        select2_css:
            inputs:
                - "%kernel.root_dir%/../vendor/ivaynberg/select2/select2.css"
                - "%kernel.root_dir%/../vendor/ivaynberg/select2/select2-bootstrap.css"
        select2_png:
            inputs:
                - "%kernel.root_dir%/../vendor/ivaynberg/select2/select2.png"
            output: "css/select2.png"
        select2_spinner_gif:
            inputs:
                - "%kernel.root_dir%/../vendor/ivaynberg/select2/select2-spinner.gif"
            output: "css/select2-spinner.gif"
        datatables_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/datatables/media/js/jquery.dataTables.min.js"
                - "%campaignchain.bower.asset_dir%/campaignchaincore/datatables/media/js/dataTables.bootstrap.min.js"
        datatables_css:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/datatables/media/css/dataTables.bootstrap.min.css"
        datatables_sort_asc:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/datatables/media/images/sort_asc.png"
            output: "images/sort_asc.png"
        datatables_sort_asc_disabled:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/datatables/media/images/sort_asc_disabled.png"
            output: "images/sort_asc_disabled.png"
        datatables_sort_both:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/datatables/media/images/sort_both.png"
            output: "images/sort_both.png"
        datatables_sort_desc:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/datatables/media/images/sort_desc.png"
            output: "images/sort_desc.png"
        datatables_sort_desc_disabled:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/datatables/media/images/sort_desc_disabled.png"
            output: "images/sort_desc_disabled.png"
        daterangepicker_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/bootstrap-daterangepicker/daterangepicker.js"
        daterangepicker_css:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/bootstrap-daterangepicker/daterangepicker-bs3.css"
        dhtmlxgantt_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/gantt/codebase/dhtmlxgantt.js"
        dhtmlxgantt_tooltip_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/gantt/codebase/ext/dhtmlxgantt_tooltip.js"
        campaignchain_dhtmlxgantt_pre_init_global_js:
            inputs:
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/dhtmlxgantt/pre_init_global.js"
        campaignchain_dhtmlxgantt_toolbar_absolute_dates_js:
            inputs:
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/dhtmlxgantt/toolbar_absolute_dates.js"
        campaignchain_dhtmlxgantt_pre_init_absolute_dates_js:
            inputs:
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/dhtmlxgantt/pre_init_global.js"
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/dhtmlxgantt/pre_init_absolute_dates.js"
        campaignchain_dhtmlxgantt_post_init_absolute_dates_js:
            inputs:
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/dhtmlxgantt/post_init_global.js"
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/dhtmlxgantt/post_init_absolute_dates.js"
        campaignchain_dhtmlxgantt_toolbar_relative_dates_js:
            inputs:
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/dhtmlxgantt/toolbar_relative_dates.js"
        campaignchain_dhtmlxgantt_pre_init_relative_dates_js:
            inputs:
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/dhtmlxgantt/pre_init_global.js"
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/dhtmlxgantt/pre_init_relative_dates.js"
        campaignchain_dhtmlxgantt_post_init_relative_dates_js:
            inputs:
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/dhtmlxgantt/post_init_global.js"
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/dhtmlxgantt/post_init_relative_dates.js"
        dhtmlxgantt_css:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/gantt/codebase/dhtmlxgantt.css"
                - "@CampaignChainCoreBundle/Resources/public/css/campaignchain/dhtmlxgantt.css"
        d3_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/d3/d3.min.js"
        d3_sankey_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/d3-plugins/sankey/sankey.js"
        flot_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/flot/jquery.flot.js"
                - "%campaignchain.bower.asset_dir%/campaignchaincore/flot/jquery.flot.time.js"
                - "%campaignchain.bower.asset_dir%/campaignchaincore/flot/jquery.flot.symbol.js"
                - "%campaignchain.bower.asset_dir%/campaignchaincore/flot/jquery.flot.crosshair.js"
        flot_comments_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/jquery.flot.comments/jquery.flot.comments.js"
        flot_tooltip_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/flot.tooltip/js/jquery.flot.tooltip.js"
        campaignchain_flot_css:
            inputs:
                - "@CampaignChainCoreBundle/Resources/public/css/campaignchain/flot.css"
        fullcalendar_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/fullcalendar/dist/fullcalendar.js"
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/fullcalendar.js"
        fullcalendar_css:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/fullcalendar/dist/fullcalendar.css"
                - "@CampaignChainCoreBundle/Resources/public/css/campaignchain/fullcalendar.css"
        countdown_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/jquery.countdown/dist/jquery.countdown.js"
        ladda_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/ladda/dist/spin.min.js"
                - "%campaignchain.bower.asset_dir%/campaignchaincore/ladda/dist/ladda.min.js"
        ladda_css:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/ladda/dist/ladda-themeless.min.css"
        blockui_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/blockui/jquery.blockUI.js"
                - "@CampaignChainCoreBundle/Resources/public/js/campaignchain/blockui.js"
        hideshowpassword_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/hideshowpassword/hideShowPassword.min.js"
        hideshowpassword_css:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/hideshowpassword/css/example.minimal.css"
                - "@CampaignChainCoreBundle/Resources/public/css/campaignchain/hideshowpassword.css"
        intro_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/intro.js/minified/intro.min.js"
        intro_css:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/intro.js/minified/introjs.min.css"
        require_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/requirejs/require.js"
        twitter_text_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/twitter-text/js/twitter-text.js"
        highlight_textarea_js:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/jquery-ui/jquery-ui.min.js"
                - "%campaignchain.bower.asset_dir%/campaignchaincore/jquery-highlighttextarea/jquery.highlighttextarea.min.js"
        highlight_textarea_css:
            inputs:
                - "%campaignchain.bower.asset_dir%/campaignchaincore/jquery-ui/themes/base/jquery-ui.min.css"
                - "%campaignchain.bower.asset_dir%/campaignchaincore/jquery-highlighttextarea/jquery.highlighttextarea.min.css"
    bundles:
        - "CampaignChainCoreBundle"
        - "FOSUserBundle"
braincrafted_bootstrap:
    output_dir: null
    assets_dir: "%kernel.root_dir%/../vendor/twbs/bootstrap"
    jquery_path: "%kernel.root_dir%/../components/jquery/jquery.js"
    less_filter: "lessphp"
    auto_configure:
        assetic: true
        twig: true
        knp_menu: true
        knp_paginator: true
    customize:
        variables_file: null
        bootstrap_output: "%kernel.root_dir%/../vendor/twbs/less/bootstrap.less"
        bootstrap_template: "BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig"
sc_datetimepicker:
    picker: null
fos_user:
    db_driver: "orm"
    firewall_name: "main"
    user_class: "CampaignChain\\CoreBundle\\Entity\\User"
    group:
        group_class: "CampaignChain\\CoreBundle\\Entity\\Group"
    from_email:
            address:        "%mailer_sender_address%"
            sender_name:    "%mailer_sender_name%"

sp_bower:
    allow_root: true
    assetic:
        enabled: false
    bundles:
        CampaignChainCoreBundle:
            asset_dir: "%campaignchain.bower.asset_dir%"
            cache: "%campaignchain.bower.cache_dir%/campaignchaincore"
sonata_block:
    default_contexts:
        - "sonata_page_bundle"
    blocks:
        sonata.block.service.text: null
        sonata.block.service.rss: null
        campaignchain.block.activity.upcoming.listgroup: null
        campaignchain.block.milestone.upcoming.listgroup: null
        campaignchain.block.campaign.ongoing.listgroup: null
        campaignchain.block.rss: null

knp_gaufrette:
    stream_wrapper: ~
    adapters:
        images:
            local:
                directory: '%campaignchain.core.upload_storage.path%'
                create: true
    filesystems:
        images:
            adapter: images

oneup_uploader:
    mappings:
        avatar:
            frontend: blueimp
            storage:
                type: gaufrette
                filesystem: gaufrette.images_filesystem
                stream_wrapper: gaufrette://images/
            allowed_mimetypes:
                - image/jpeg
                - image/png
                - image/gif
        hook_image:
            frontend: blueimp
            storage:
                type: gaufrette
                filesystem: gaufrette.images_filesystem
                stream_wrapper: gaufrette://images/
            allowed_mimetypes:
                - image/jpeg
                - image/png
                - image/gif
liip_imagine:
    loaders:
        stream_loader:
            stream:
                wrapper: gaufrette://images/
    data_loader: stream_loader
    filter_sets:
        auto_rotate:
            filters:
                auto_rotate: ~
        cropper:
            filters:
                crop: ~
                rotate: ~
        navbar_avatar:
            filters:
                thumbnail: {size: [24, 24], mode: outbound}
        avatar:
            filters:
                thumbnail: {size: [200, 200], mode: outbound}

sensio_framework_extra:
    request: { converters: true }

fos_rest:
    disable_csrf_role: ROLE_API
    versioning:
        enabled: true
        default_version: v1
        resolvers:
            query:
                enabled: true
            custom_header:
                enabled: false
            media_type:
                enabled: false
        guessing_order:
            - query
    routing_loader:
        default_format: json
        include_format: false
    param_fetcher_listener: true
    body_listener: true
    body_converter:
        enabled: true
    view:
        formats:
            json: true
            xml: false
        templating_formats:
            html: false
    format_listener:
        rules:
            - { path: '^/api/{version}', priorities: ['json'], fallback_format: json, attributes: { _controller: FOS\RestBundle\Controller\ExceptionController }, prefer_extension: true }
            - { path: '^/', stop: true } # Turn off format listener
    access_denied_listener:
        json: true
    view:
        force_redirects:
            json: true

nelmio_api_doc:
    name: CampaignChain API v1 (beta)
    motd:
        template: 'CampaignChainCoreBundle:REST:motd.html.twig'
    sandbox:
        request_format:
            formats:
                json: application/json