# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_core_install:
    pattern: /install/
    defaults: { _controller: CampaignChainCoreBundle:Install:check }

campaignchain_core_install_step:
    pattern: /install/step/{index}
    defaults: { _controller: CampaignChainCoreBundle:Install:step }

campaignchain_core_homepage:
    pattern:  /
    defaults: { _controller: CampaignChainCoreBundle:About:index }
    options:
        campaignchain:
            description: The start page
            rest:
                expose: true

campaignchain_core_about:
    pattern:  /about/
    defaults: { _controller: CampaignChainCoreBundle:About:index }
    options:
        campaignchain:
            description: Read about CampaignChain
            rest:
                expose: true

campaignchain_core_plan:
    pattern:  /plan/{id}
    defaults: { _controller: CampaignChainCoreBundle:Plan:index, id: 0 }
    options:
        campaignchain:
            description: Plan campaigns
            rest:
                expose: true

campaignchain_core_execute:
    pattern:  /execute/
    defaults: { _controller: CampaignChainCoreBundle:Execute:index }
    options:
        campaignchain:
            description: View upcoming actions
            rest:
                expose: true

campaignchain_core_campaign:
    pattern:  /campaigns/
    defaults: { _controller: CampaignChainCoreBundle:Campaign:index }

campaignchain_core_campaign_new:
    pattern:  /campaign/new/
    defaults: { _controller: CampaignChainCoreBundle:Campaign:new }
    options:
        campaignchain:
            description: Create a new campaign
            rest:
                expose: true

campaignchain_core_campaign_edit:
    pattern:  /campaign/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Campaign:edit }

campaignchain_core_campaign_edit_modal:
    pattern:  /modal/campaign/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Campaign:editModal }
    options:
        expose: true

campaignchain_core_campaign_edit_api:
    pattern:  /api/private/campaign/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Campaign:editApi }
    options:
        expose: true

campaignchain_core_campaign_move_api:
    pattern:  /api/private/campaign/move
    defaults: { _controller: CampaignChainCoreBundle:Campaign:moveApi }
    methods:  [POST]
    options:
        expose: true

campaignchain_core_activities:
    pattern:  /activities/
    defaults: { _controller: CampaignChainCoreBundle:Activity:index }
    options:
        campaignchain:
            description: View all activities
            rest:
                expose: true

campaignchain_core_activities_new:
    pattern:  /activity/new/
    defaults: { _controller: CampaignChainCoreBundle:Activity:new }
    options:
        campaignchain:
            description: Create a new activity
            rest:
                expose: true

campaignchain_core_activity_edit:
    pattern:  /activity/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Activity:edit }

campaignchain_core_activity_edit_modal:
    pattern:  /modal/activity/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Activity:editModal }
    options:
        expose: true

campaignchain_core_activity_edit_api:
    pattern:  /api/private/activity/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Activity:editApi }
    options:
        expose: true

campaignchain_core_activity_move_api:
    pattern:  /api/private/activity/move
    defaults: { _controller: CampaignChainCoreBundle:Activity:moveApi }
    methods:  [POST]
    options:
        expose: true

campaignchain_core_activity_read:
    pattern:  /activity/{id}
    defaults: { _controller: CampaignChainCoreBundle:Activity:read }

campaignchain_core_milestone:
    pattern:  /milestones/
    defaults: { _controller: CampaignChainCoreBundle:Milestone:index }
    options:
        campaignchain:
            description: View all milestones
            rest:
                expose: true

campaignchain_core_milestone_new:
    pattern:  /milestone/new/
    defaults: { _controller: CampaignChainCoreBundle:Milestone:new }
    options:
        campaignchain:
            description: Create a new milestone
            rest:
                expose: true

campaignchain_core_milestone_edit:
    pattern:  /milestone/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Milestone:edit }

campaignchain_core_milestone_edit_modal:
    pattern:  /modal/milestone/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Milestone:editModal }
    options:
        expose: true

campaignchain_core_milestone_edit_api:
    pattern:  /api/private/milestone/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Milestone:editApi }
    options:
        expose: true

campaignchain_core_milestone_move_api:
    pattern:  /api/private/milestone/move
    defaults: { _controller: CampaignChainCoreBundle:Milestone:moveApi }
    methods:  [POST]
    options:
        expose: true

campaignchain_core_report:
    pattern:  /reports/{id}
    defaults: { _controller: CampaignChainCoreBundle:Report:index, id: 0 }
    options:
        campaignchain:
            description: View all reports
            rest:
                expose: true

campaignchain_core_module:
    pattern:  /modules/
    defaults: { _controller: CampaignChainCoreBundle:Module:index }
    options:
        campaignchain:
            description: Manage modules
            rest:
                expose: true

campaignchain_core_module_new:
    pattern:  /modules/new/
    defaults: { _controller: CampaignChainCoreBundle:Module:new }
    options:
        campaignchain:
            description: Add new modules
            rest:
                expose: true

campaignchain_core_channel:
    pattern:  /channels/
    defaults: { _controller: CampaignChainCoreBundle:Channel:index }
    options:
        campaignchain:
            description: View all channels
            rest:
                expose: true

campaignchain_core_channel_new:
    pattern:  /channel/new/
    defaults: { _controller: CampaignChainCoreBundle:Channel:new }
    options:
        campaignchain:
            description: Connect a new channel location
            rest:
                expose: true

campaignchain_core_channel_cta_test:
    pattern: channel/{id}/cta-tracking/
    defaults: { _controller: CampaignChainCoreBundle:Channel:ctaTracking, id: 0  }

campaignchain_core_channel_cta_tracking_test:
    pattern:  /api/private/channel/{id}/cta-tracking/test
    defaults: { _controller: CampaignChainCoreBundle:Channel:apiTestCtaTracking, id: 0 }

campaignchain_core_report_list_cta_locations_per_campaign_api:
    pattern:  /api/private/report/cta/campaign/{id}/locations
    defaults: { _controller: CampaignChainCoreBundle:Report:apiListCtaLocationsPerCampaign }
    options:
        expose: true

campaignchain_core_location:
    pattern:  /locations/
    defaults: { _controller: CampaignChainCoreBundle:Location:index }
    options:
        campaignchain:
            description: View all locations
            rest:
                expose: true

campaignchain_core_location_list_activities_api:
    pattern:  /api/private/location/{id}/activities
    defaults: { _controller: CampaignChainCoreBundle:Location:apiListActivities }
    options:
        expose: true

campaignchain_core_tracking_new_api:
    pattern:  /api/v1/report/cta/new/{channel}
    defaults: { _controller: CampaignChainCoreBundle:Tracking:newApi }
#    methods:  [POST]

# Developer Tools

campaignchain_development_sample_data:
    pattern:  /development/sample-data
    defaults: { _controller: CampaignChainCoreBundle:Development:sampleData }

campaignchain_development_reset_system:
    pattern:  /development/reset-system
    defaults: { _controller: CampaignChainCoreBundle:Development:resetSystem }

# User management

campaignchain_core_user:
    pattern:  /users/
    defaults: { _controller: CampaignChainCoreBundle:User:index }
    options:
        campaignchain:
            description: Manage users
            rest:
                expose: true

campaignchain_core_profile_edit:
    pattern:  /profile/edit/{id}
    defaults: { _controller: CampaignChainCoreBundle:Profile:edit }

campaignchain_core_profile_change_password:
    pattern:  /profile/change_password/{id}
    defaults: { _controller: CampaignChainCoreBundle:Profile:changePassword }

campaignchain_core_profile_grab_gavatar:
    pattern: /profile/grab_gravatar
    defaults: { _controller: CampaignChainCoreBundle:Profile:grabGravatar }
    methods: [POST]

campaignchain_core_profile_preview_gravatar:
    pattern: /profile/preview_gravatar
    defaults: { _controller: CampaignChainCoreBundle:Profile:previewGravatar }

campaignchain_core_profile_crop_avatar:
    pattern: /profile/crop_avatar
    defaults: { _controller: CampaignChainCoreBundle:Profile:cropAvatar }
    methods: [POST]

campaignchain_core_user_new:
    path: /users/new
    defaults: { _controller: CampaignChainCoreBundle:User:new }
    options:
        campaignchain:
            description: Create a new user
            rest:
                expose: true

# FOS User

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /user/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /user/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /user/resetting

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

# FOS JavaScript routing

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

oneup_uploader:
    resource: .
    type: uploader

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# REST routes are being created automatically via FOSRestBundle.
campaignchain_core_rest_root:
    type:     rest
    prefix:   /api/{version}
    resource: CampaignChain\CoreBundle\Controller\REST\RootController

campaignchain_core_rest_package:
    type:     rest
    prefix:   /api/{version}/packages
    resource: CampaignChain\CoreBundle\Controller\REST\PackageController

# This route accepts a Composer package name, which requires that we surpase
# Symfony's default exlusion of / in route parameters.
campaignchain_core_rest_package_get_packages_package:
    path: /api/{version}/packages/{package}
    defaults: { _controller: CampaignChainCoreBundle:REST/Package:getPackages }
    methods: [GET]
    requirements:
        package: ".+"

campaignchain_core_rest_module:
    type:     rest
    prefix:   /api/{version}/modules
    resource: CampaignChain\CoreBundle\Controller\REST\ModuleController

# This route accepts a Module URI, which requires that we surpase Symfony's
# default exlusion of / in route parameters.
campaignchain_core_rest_module_get_modules_uris_uri:
    path: /api/{version}/modules/uris/{uri}
    defaults: { _controller: CampaignChainCoreBundle:REST/Module:getUris }
    methods: [GET]
    requirements:
        uri: ".+"

# This route accepts a Composer package name, which requires that we surpase
# Symfony's default exlusion of / in route parameters.
campaignchain_core_rest_module_get_modules_packages_package:
    path: /api/{version}/modules/packages/{package}
    defaults: { _controller: CampaignChainCoreBundle:REST/Module:getPackages }
    methods: [GET]
    requirements:
        package: ".+"

campaignchain_core_rest_channel:
    type:     rest
    prefix:   /api/{version}/channels
    resource: CampaignChain\CoreBundle\Controller\REST\ChannelController

# This route accept a URL, which requires that we surpase Symfony's default
# exlusion of / in route parameters.
campaignchain_core_rest_channel_get_channels_locations_urls_url:
    path: /api/{version}/channels/locations/urls/{url}
    defaults: { _controller: CampaignChainCoreBundle:REST/Channel:getLocationsUrls }
    methods: [GET]
    requirements:
        url: ".+"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc