# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

campaignchain_core_install:
    pattern: /install/
    defaults: { _controller: CampaignChainCoreBundle:Install:check }

campaignchain_core_install_step:
    pattern: /install/step/{index}
    defaults: { _controller: CampaignChainCoreBundle:Install:step }

campaignchain_core_homepage:
    pattern:  /
    defaults: { _controller: CampaignChainCoreBundle:About:index }

campaignchain_core_about:
    pattern:  /about/
    defaults: { _controller: CampaignChainCoreBundle:About:index }

campaignchain_core_plan:
    pattern:  /plan/{id}
    defaults: { _controller: CampaignChainCoreBundle:Plan:index, id: 0 }

campaignchain_core_execute:
    pattern:  /execute/
    defaults: { _controller: CampaignChainCoreBundle:Execute:index }

campaignchain_core_campaign:
    pattern:  /campaigns/
    defaults: { _controller: CampaignChainCoreBundle:Campaign:index }

campaignchain_core_campaign_new:
    pattern:  /campaign/new/
    defaults: { _controller: CampaignChainCoreBundle:Campaign:new }

campaignchain_core_campaign_edit:
    pattern:  /campaign/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Campaign:edit }

campaignchain_core_campaign_edit_modal:
    pattern:  /modal/campaign/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Campaign:editModal }
    options:
        expose: true

campaignchain_core_campaign_edit_api:
    pattern:  /api/private/campaign/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Campaign:editApi }
    options:
        expose: true

campaignchain_core_campaign_move_api:
    pattern:  /api/private/campaign/move
    defaults: { _controller: CampaignChainCoreBundle:Campaign:moveApi }
    methods:  [POST]
    options:
        expose: true

campaignchain_core_activities:
    pattern:  /activities/
    defaults: { _controller: CampaignChainCoreBundle:Activity:index }

campaignchain_core_activities_new:
    pattern:  /activity/new/
    defaults: { _controller: CampaignChainCoreBundle:Activity:new }

campaignchain_core_activity_edit:
    pattern:  /activity/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Activity:edit }

campaignchain_core_activity_edit_modal:
    pattern:  /modal/activity/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Activity:editModal }
    options:
        expose: true

campaignchain_core_activity_edit_api:
    pattern:  /api/private/activity/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Activity:editApi }
    options:
        expose: true

campaignchain_core_activity_move_api:
    pattern:  /api/private/activity/move
    defaults: { _controller: CampaignChainCoreBundle:Activity:moveApi }
    methods:  [POST]
    options:
        expose: true

campaignchain_core_activity_read:
    pattern:  /activity/{id}
    defaults: { _controller: CampaignChainCoreBundle:Activity:read }

campaignchain_core_milestone:
    pattern:  /milestones/
    defaults: { _controller: CampaignChainCoreBundle:Milestone:index }

campaignchain_core_milestone_new:
    pattern:  /milestone/new/
    defaults: { _controller: CampaignChainCoreBundle:Milestone:new }

campaignchain_core_milestone_edit:
    pattern:  /milestone/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Milestone:edit }

campaignchain_core_milestone_edit_modal:
    pattern:  /modal/milestone/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Milestone:editModal }
    options:
        expose: true

campaignchain_core_milestone_edit_api:
    pattern:  /api/private/milestone/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Milestone:editApi }
    options:
        expose: true

campaignchain_core_milestone_move_api:
    pattern:  /api/private/milestone/move
    defaults: { _controller: CampaignChainCoreBundle:Milestone:moveApi }
    methods:  [POST]
    options:
        expose: true

campaignchain_core_report:
    pattern:  /reports/{id}
    defaults: { _controller: CampaignChainCoreBundle:Report:index, id: 0 }

campaignchain_core_module:
    pattern:  /modules/
    defaults: { _controller: CampaignChainCoreBundle:Module:index }

campaignchain_core_module_new:
    pattern:  /modules/new/
    defaults: { _controller: CampaignChainCoreBundle:Module:new }

campaignchain_core_channel:
    pattern:  /channels/
    defaults: { _controller: CampaignChainCoreBundle:Channel:index }

campaignchain_core_channel_new:
    pattern:  /channel/new/
    defaults: { _controller: CampaignChainCoreBundle:Channel:new }

campaignchain_core_channel_cta_test:
    pattern: channel/{id}/cta-tracking/
    defaults: { _controller: CampaignChainCoreBundle:Channel:ctaTracking, id: 0  }

campaignchain_core_channel_cta_tracking_test:
    pattern:  /api/private/channel/{id}/cta-tracking/test
    defaults: { _controller: CampaignChainCoreBundle:Channel:apiTestCtaTracking, id: 0 }

campaignchain_core_report_list_cta_locations_per_campaign_api:
    pattern:  /api/private/report/cta/campaign/{id}/locations
    defaults: { _controller: CampaignChainCoreBundle:Report:apiListCtaLocationsPerCampaign }
    options:
        expose: true

campaignchain_core_location:
    pattern:  /locations/
    defaults: { _controller: CampaignChainCoreBundle:Location:index }

campaignchain_core_location_list_activities_api:
    pattern:  /api/private/location/{id}/activities
    defaults: { _controller: CampaignChainCoreBundle:Location:apiListActivities }
    options:
        expose: true

campaignchain_core_tracking_new_api:
    pattern:  /api/v1/report/cta/new/{channel}
    defaults: { _controller: CampaignChainCoreBundle:Tracking:newApi }
#    methods:  [POST]

# Developer Tools

campaignchain_development_sample_data:
    pattern:  /development/sample-data
    defaults: { _controller: CampaignChainCoreBundle:Development:sampleData }

campaignchain_development_reset_system:
    pattern:  /development/reset-system
    defaults: { _controller: CampaignChainCoreBundle:Development:resetSystem }

# User management

campaignchain_core_user:
    pattern:  /users/
    defaults: { _controller: CampaignChainCoreBundle:User:index }

campaignchain_core_profile_edit:
    pattern:  /profile/edit/{id}
    defaults: { _controller: CampaignChainCoreBundle:Profile:edit }

campaignchain_core_profile_change_password:
    pattern:  /profile/change_password/{id}
    defaults: { _controller: CampaignChainCoreBundle:Profile:changePassword }

campaignchain_core_user_new:
    path: /users/new
    defaults: { _controller: CampaignChainCoreBundle:User:new }

# FOS User

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

#fos_user_profile:
#    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#    prefix: /user/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /user/register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /user/resetting

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group

# FOS JavaScript routing

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

oneup_uploader:
    resource: .
    type: uploader

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"