# Copyright 2016 CampaignChain, Inc. <info@campaignchain.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# installation wizard routes
campaignchain_core_install:
    pattern: /install/
    defaults: { _controller: CampaignChainCoreBundle:Install:check }

campaignchain_core_install_step:
    pattern: /install/step/{index}
    defaults: { _controller: CampaignChainCoreBundle:Install:step }

# main routes
campaignchain_core_homepage:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Redirect:redirect
        route: campaignchain_core_plan
        permanent: true
    options:
        campaignchain:
            description: The start page
            rest:
                expose: true

campaignchain_core_about:
    pattern:  /about/
    defaults: { _controller: CampaignChainCoreBundle:About:index }
    options:
        campaignchain:
            description: Read about CampaignChain
            rest:
                expose: true

campaignchain_core_plan:
    pattern:  /plan/campaigns/
    defaults: { _controller: CampaignChainCoreBundle:Plan:campaigns }
    options:
        campaignchain:
            description: Plan campaigns
            rest:
                expose: true

campaignchain_core_plan_activities:
    pattern:  /plan/activities/
    defaults: { _controller: CampaignChainCoreBundle:Plan:activities }
    options:
        campaignchain:
            description: Plan activities
            rest:
                expose: true

campaignchain_core_plan_templates:
    pattern:  /plan/templates/
    defaults: { _controller: CampaignChainCoreBundle:Plan:templates }
    options:
        campaignchain:
            description: Plan templates
            rest:
                expose: true

campaignchain_core_execute:
    pattern:  /execute/
    defaults: { _controller: CampaignChainCoreBundle:Execute:index }
    options:
        campaignchain:
            description: View upcoming actions
            rest:
                expose: true

# campaign routes
campaignchain_core_campaign:
    pattern:  /campaigns/
    defaults: { _controller: CampaignChainCoreBundle:Campaign:index }

campaignchain_core_campaign_new:
    pattern:  /campaign/new/
    defaults: { _controller: CampaignChainCoreBundle:Campaign:new }
    options:
        expose: true
        campaignchain:
            description: Create a new campaign
            rest:
                expose: true

campaignchain_core_campaign_edit:
    pattern:  /campaign/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Campaign:edit }

campaignchain_core_campaign_edit_modal:
    pattern:  /modal/campaign/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Campaign:editModal }
    options:
        expose: true

# activity routes
campaignchain_core_activities:
    pattern:  /activities/
    defaults: { _controller: CampaignChainCoreBundle:Activity:index }
    options:
        campaignchain:
            description: View all activities
            rest:
                expose: true

campaignchain_core_activities_new:
    pattern:  /activity/new/
    defaults: { _controller: CampaignChainCoreBundle:Activity:new }
    options:
        campaignchain:
            description: Create a new activity
            rest:
                expose: true

campaignchain_core_activity_remove:
    pattern:  /activity/{id}/remove
    defaults: { _controller: CampaignChainCoreBundle:Activity:remove }

campaignchain_core_activity_edit:
    pattern:  /activity/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Activity:edit }

campaignchain_core_activity_edit_modal:
    pattern:  /modal/activity/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Activity:editModal }
    options:
        expose: true

campaignchain_core_activity_read:
    pattern:  /activity/{id}
    defaults: { _controller: CampaignChainCoreBundle:Activity:read }

# milestone routes
campaignchain_core_milestone:
    pattern:  /milestones/
    defaults: { _controller: CampaignChainCoreBundle:Milestone:index }
    options:
        campaignchain:
            description: View all milestones
            rest:
                expose: true

campaignchain_core_milestone_new:
    pattern:  /milestone/new/
    defaults: { _controller: CampaignChainCoreBundle:Milestone:new }
    options:
        campaignchain:
            description: Create a new milestone
            rest:
                expose: true

campaignchain_core_milestone_edit:
    pattern:  /milestone/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Milestone:edit }

campaignchain_core_milestone_edit_modal:
    pattern:  /modal/milestone/{id}/edit
    defaults: { _controller: CampaignChainCoreBundle:Milestone:editModal }
    options:
        expose: true

campaignchain_core_milestone_remove:
    pattern:  /milestone/{id}/remove
    defaults: { _controller: CampaignChainCoreBundle:Milestone:remove }

# report routes
campaignchain_core_report:
    pattern:  /reports
    defaults: { _controller: CampaignChainCoreBundle:Report:index }
    options:
        campaignchain:
            description: View all reports
            rest:
                expose: true

campaignchain_core_report_show:
    pattern:  /report/{id}
    defaults: { _controller: CampaignChainCoreBundle:Report:show }

# module routes
campaignchain_core_module:
    pattern:  /modules/
    defaults: { _controller: CampaignChainCoreBundle:Module:index }
    options:
        campaignchain:
            description: Manage modules
            rest:
                expose: true

campaignchain_core_module_new:
    pattern:  /modules/new/
    defaults: { _controller: CampaignChainCoreBundle:Module:new }
    options:
        campaignchain:
            description: Add new modules
            rest:
                expose: true

# channel routes
campaignchain_core_channel:
    pattern:  /channels/
    defaults: { _controller: CampaignChainCoreBundle:Channel:index }
    options:
        campaignchain:
            description: View all channels
            rest:
                expose: true

campaignchain_core_channel_new:
    pattern:  /channel/new/{id}
    defaults: { _controller: CampaignChainCoreBundle:Channel:new }
    options:
        campaignchain:
            description: Connect a new channel location
            rest:
                expose: true

campaignchain_core_channel_cta_test:
    pattern: channel/{id}/cta-tracking/
    defaults: { _controller: CampaignChainCoreBundle:Channel:ctaTracking, id: 0  }

campaignchain_core_channel_remove:
    pattern:  /channel/{id}/remove
    defaults: { _controller: CampaignChainCoreBundle:Channel:remove }

campaignchain_core_channel_toggle_status:
    pattern:  /channel/{id}/toggleStatus
    defaults: { _controller: CampaignChainCoreBundle:Channel:toggleStatus }

# location routes
campaignchain_core_location:
    pattern:  /locations/
    defaults: { _controller: CampaignChainCoreBundle:Location:index }
    options:
        campaignchain:
            description: View all locations
            rest:
                expose: true

campaignchain_core_location_remove:
    pattern:  /location/{id}/remove
    defaults: { _controller: CampaignChainCoreBundle:Location:remove }

campaignchain_core_location_toggle_status:
    pattern:  /location/{id}/toggleDisabling
    defaults: { _controller: CampaignChainCoreBundle:Location:toggleStatus }

# tracking routes
campaignchain_core_tracking_js:
    resource: .
    type: trackingjs

campaignchain_core_tracking_js_old:
    pattern:  /bundles/campaignchaincore/js/campaignchain/campaignchain_tracking.js
    defaults: { _controller: CampaignChainCoreBundle:Tracking:trackingJs }

campaignchain_core_tracking_js_test:
    path:     /test/trackingjs/{channel}/{dev}/{old}
    defaults: { _controller: CampaignChainCoreBundle:Tracking:testTrackingJs, dev: 1, old: 0 }
    condition: "request.getScriptName() == '/app_dev.php'"

# developer tools
campaignchain_development_sample_data:
    pattern:  /development/sample-data
    defaults: { _controller: CampaignChainCoreBundle:Development:sampleData }
    condition: "request.getScriptName() == '/app_dev.php'"

campaignchain_development_reset_system:
    pattern:  /development/reset-system
    defaults: { _controller: CampaignChainCoreBundle:Development:resetSystem }
    condition: "request.getScriptName() == '/app_dev.php'"

# theme settings
campaignchain_core_theme_settings:
    pattern:  /theme/settings
    defaults: { _controller: CampaignChainCoreBundle:Theme:settings }

# user management routes
campaignchain_core_user:
    pattern:  /user/list
    defaults: { _controller: CampaignChainCoreBundle:User:index }
    options:
        campaignchain:
            description: Manage users
            rest:
                expose: true

campaignchain_core_user_new:
    path: /user/new
    defaults: { _controller: CampaignChainCoreBundle:User:new }
    options:
        campaignchain:
            description: Create a new user
            rest:
                expose: true

campaignchain_core_user_edit:
    pattern:  /user/edit/{id}
    defaults: { _controller: CampaignChainCoreBundle:User:edit }

campaignchain_core_theme_profile:
    pattern:  /user/edit/{ident}
    defaults: { _controller: CampaignChainCoreBundle:User:edit }
    options:
        avanzu_admin_route: profile

campaignchain_core_user_change_password:
    pattern:  /user/change_password/{id}
    defaults: { _controller: CampaignChainCoreBundle:User:changePassword }

campaignchain_core_user_toggle_enabling:
    pattern:  /user/toggle_enable/{id}
    defaults: { _controller: CampaignChainCoreBundle:User:toggleEnabling }
    options:
        campaignchain:
            description: Deactivate a user
            rest:
                expose: true

# profile routes
campaignchain_core_profile_edit:
    pattern:  /profile/edit
    defaults: { _controller: CampaignChainCoreBundle:Profile:edit }

campaignchain_core_profile_change_password:
    pattern:  /profile/change_password
    defaults: { _controller: CampaignChainCoreBundle:Profile:changePassword }

campaignchain_core_profile_grab_gavatar:
    pattern: /profile/grab_gravatar
    defaults: { _controller: CampaignChainCoreBundle:Profile:grabGravatar }
    methods: [POST]

campaignchain_core_profile_preview_gravatar:
    pattern: /profile/preview_gravatar
    defaults: { _controller: CampaignChainCoreBundle:Profile:previewGravatar }

campaignchain_core_profile_crop_avatar:
    pattern: /profile/crop_avatar
    defaults: { _controller: CampaignChainCoreBundle:Profile:cropAvatar }
    methods: [POST]


# User / security routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /user/resetting

campaignchain_core_security_resume:
    pattern:  /resume
    defaults: { _controller: CampaignChainCoreBundle:Security:resume }
    options:
        expose: true

# FOSJsRoutingBundle routes
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# OneupUploaderBundle routes
oneup_uploader:
    resource: "@OneupUploaderBundle/Resources/config/uploader.xml"
    type: uploader

# LiipImagineBundle routes
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

# Public REST routes are being created automatically via FOSRestBundle.
campaignchain_core_rest_private:
    resource: "@CampaignChainCoreBundle/Resources/config/routing_rest_private.yml"
    prefix: /api/private

# Public REST routes are being created automatically via FOSRestBundle.
campaignchain_core_rest_public:
    resource: "@CampaignChainCoreBundle/Resources/config/routing_rest_public.yml"
    prefix: /api/v1

# NelmioApiDocBundle routes
NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc