# This file is part of the CampaignChain package.
#
# (c) CampaignChain Inc. <info@campaignchain.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

#CampaignChainCoreBundle\Entity\Campaign:
#    properties:
#        name:
#            - NotBlank: ~
#        startDate:
#            - NotBlank: ~
#            - Type: \DateTime
#        endDate:
#            - NotBlank: ~
#            - Type: \DateTime

CampaignChainCoreBundle\Entity\Activity:
    properties:
        name:
            - NotBlank: ~
        campaignId:
            - NotBlank: ~
            - Type: int
        channelId:
            - NotBlank: ~
            - Type: int